In [1]:
from tabula import read_pdf
from tabulate import tabulate
import pandas as pd

In [7]:
pdf_contents = read_pdf("Report_1600821.pdf", pages="all", multiple_tables=True)

In [8]:
pdf_content = pdf_contents
pdf_content.pop(0)
pdf_content.pop(60)

,0,1,2,3
0,NaN,NaN,Suppliers Imported,NaN
1,Import Action,Supplier,NaN,Supplier Number
2,UPDATE,Mark W LaChey dba Law Office of Mark W LaChey-...,NaN,ab:87961
3,Total Suppliers Imported,1,NaN,NaN

In [15]:
report_df = pd.DataFrame()
for i in range(len(pdf_content)):
    page = pdf_content[i]
    page = page.drop(page.index[:2])
    page = page.drop([1,3,5], axis=1)
    report_df = pd.concat([report_df, page])

In [16]:
report_df = report_df.rename(columns={0:'Interface ID',2 : 'Supplier', 4 : 'Rejection Reason' , 6 : ' Value'})

In [17]:
report_df

,Interface ID,Supplier,Rejection Reason,Value
2,9936,1 Retail Investments\rSales Team In Southern\r...,The value provided is invalid.,1 Retail Investments Sales\rTeam In Southern C...
3,9848,1131 Thurow-\rCMP_52251,The value provided is invalid.,1131 Thurow-CMP_52251
4,9628,1228 Harding Avenue-\rCMP_43179,The value provided is invalid.,1228 Harding Avenue-\rCMP_43179
5,9891,1304 S Roxbury Drive\rLLC-ab:91422,The value provided is invalid.,1304 S Roxbury Drive LLC-\rab:91422
6,9618,14929 Lone Butte Road-\rCMP_50714,The value provided is invalid.,14929 Lone Butte Road-\rCMP_50714
7,9763,1507 Watson Boulevard-\rCMP_54905,The value provided is invalid.,1507 Watson Boulevard-\rCMP_54905
8,9640,1561-81 Kennedy Blvd.\r& 265 Gates Avenue-\rCM...,The value provided is invalid.,1561-81 Kennedy Blvd. & 265\rGates Avenue-CMP_...
9,9528,2121-CMP_52224,The value provided is invalid.,2121-CMP_52224
10,9938,2257 Akr Wadsworth\rRoad-CMP_55028,The value provided is invalid.,2257 Akr Wadsworth Road-\rCMP_55028
11,9345,226 Wyckoff Avenue-\rCMP_42047,The value provided is invalid.,226 Wyckoff Avenue-\rCMP_42047
12,9748,2347 Canton Highway-\rCMP_54902,The value provided is invalid.,2347 Canton Highway-\rCMP_54902
13,10071,2nd Avenue & 1st Street\rService Station-\rCMP...,The value provided is invalid.,2nd Avenue & 1st Street\rService Station-CMP_5...
14,9578,300 & 500 East Truxton\rAve.-CMP_47839,The value provided is invalid.,300 & 500 East Truxton Ave.-\rCMP_47839
15,10107,3000 Houston Street\rDevelopment LLC-\rab:95653,The value provided is invalid.,3000 Houston Street\rDevelopment LLC-ab:95653
2,12227,33rd Street West Service\rStation-CMP_54322,The value provided is invalid.,33rd Street West Service\rStation-CMP_54322
3,10030,3611-CMP_52246,The value provided is invalid.,3611-CMP_52246
4,9772,399 Route 22 West-\rCMP_43969,The value provided is invalid.,399 Route 22 West-\rCMP_43969
5,9812,405 National Avenue-\rCMP_47849,The value provided is invalid.,405 National Avenue-\rCMP_47849
6,10148,532 South Broadway-\rCMP_51053,The value provided is invalid.,532 South Broadway-\rCMP_51053
7,9592,5355-75 South Third\rStreet-CMP_51122,The value provided is invalid.,5355-75 South Third Street-\rCMP_51122
8,9977,5725 Kearny Villa Road-\rCMP_47863,The value provided is invalid.,5725 Kearny Villa Road-\rCMP_47863
9,9493,6380 East 30th Street\rSite-CMP_45601,The value provided is invalid.,6380 East 30th Street Site-\rCMP_45601
10,9426,657 Union Boulevard,The value provided is invalid.,New Jersey-CMP_47228
11,9973,700 GOLFMORE\rASSOCIATION INC-\rGLT:CMP:4006,The value provided is invalid.,700 GOLFMORE\rASSOCIATION INC-\rGLT:CMP:4006
12,9702,702 Firm LLC dba The\r702 Firm-ab:90406,The value provided is invalid.,702 Firm LLC dba The 702\rFirm-ab:90406
13,9497,727 Bellevue Way-\rCMP_46814,The value provided is invalid.,727 Bellevue Way-\rCMP_46814
14,9717,8391 Pecos-CMP_54824,The value provided is invalid.,8391 Pecos-CMP_54824
15,9430,893 New Ashford Road-\rCMP_50452,The value provided is invalid.,893 New Ashford Road-\rCMP_50452
16,9985,95 Eastern Parkway\rCompany-ab:103764,The value provided is invalid.,95 Eastern Parkway Company-\rab:103764
17,9390,960 West Henderson-\rCMP_53359,The value provided is invalid.,960 West Henderson-\rCMP_53359
...,...,...,...,...
11,9596,White And Lavendar\rPest Contro-\rASI:CMP:10299,The value provided is invalid.,White And Lavendar Pest\rContro-ASI:CMP:10299
12,9863,Whiteside Construction\rCorp,The value provided is invalid.,Inc-ASI:CMP:10307
13,9988,Wild Game Innovations\rLlc-ASI:CMP:10318,The value provided is invalid.,Wild Game Innovations Llc-\rASI:CMP:10318
14,9852,Wilfong Food & Gas\rLlc-ASI:CMP:10323,The value provided is invalid.,Wilfong Food & Gas Llc-\rASI:CMP:10323
15,9664,Wilkins Township-\rASI:CMP:13833,The value provided is invalid.,Wilkins Township-\rASI:CMP:13833
16,9406,William Sather-\rASI:PER:10346,The value provided is invalid.,William Sather-\rASI:PER:10346
17,10122,William Shoemaker-,The value provided is invalid.,William Shoemaker-ab:99368
2,NaN,ab:99368,NaN,NaN
3,9665,William Wimmer-\rASI:PER:20554,The value provided is invalid.,William Wimmer-\rASI:PER:20554
4,9510,Williamson Yard\rFacilities-CMP_52708,The value provided is invalid.,Williamson Yard Facilities-\rCMP_52708
5,9274,Wilmington Office 775-\rLOC_775,The value provided is invalid.,Wilmington Office 775-\rLOC_775
6,9594,Win-R Insulation,The value provided is invalid.,Win-R Insulation
7,9632,Woodside 05N LP-\rab:94353,The value provided is invalid.,Woodside 05N LP-ab:94353
8,9909,World Class Demolition\rCorp-ab:56329,The value provided is invalid.,World Class Demolition Corp-\rab:56329
9,9399,Wyoming S&P-\rASI:CMP:10440,The value provided is invalid.,Wyoming S&P-\rASI:CMP:10440
10,9312,Yardley Office 23344-\rASI:LOC:23344,The value provided is invalid.,Yardley Office 23344-\rASI:LOC:23344
11,9974,York Risk Services-\rab:97024,The value provided is invalid.,York Risk Services-ab:97024
12,9273,Yvehfe Valadez-\rPER_20010,The value provided is invalid.,Yvehfe Valadez-PER_20010
13,9277,Yvonne Albanez-\rPER_22706,The value provided is invalid.,Yvonne Albanez-PER_22706
14,9922,ZZZSTANISLAUS,The value provided is invalid.,ZZZSTANISLAUS
15,10156,Zaina Thabet-\rASI:PER:14286,The value provided is invalid.,Zaina Thabet-ASI:PER:14286
16,10042,de maximus\rEnvironmental\rRemediation Fund\rA...,The value provided is invalid.,de maximus Environmental\rRemediation Fund Acc...
17,10194,insured unknown -\r14EP0942-\rMMK:CMP:461,The value provided is invalid.,insured unknown - 14EP0942-\rMMK:CMP:461
18,9296,insured unknown -\r14EP1453-\rMMK:CMP:491,The value provided is invalid.,insured unknown - 14EP1453-\rMMK:CMP:491
2,9642,insured unknown -\r28EP0297-\rMMK:CMP:583,The value provided is invalid.,insured unknown - 28EP0297-\rMMK:CMP:583
3,9739,insured unknown -\r28EP0570-\rMMK:CMP:585,The value provided is invalid.,insured unknown - 28EP0570-\rMMK:CMP:585
4,9435,insured unknown -\r4SG03724-\rMMK:CMP:713,The value provided is invalid.,insured unknown - 4SG03724-\rMMK:CMP:713
5,9328,insured unknown -\rASD03746-\rMMK:CMP:735,The value provided is invalid.,insured unknown -\rASD03746-MMK:CMP:735
6,9924,insured unknown -\rGMV00053-\rMMK:CMP:801,The value provided is invalid.,insured unknown -\rGMV00053-MMK:CMP:801
7,Total Suppliers Not Imported999,NaN,NaN,NaN